campus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views
#from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('student_register/' , views.student_register , name='student_register'),
    path('student_login/', views.student_login,name='student_login'),
    path('dept_register/' , views.dept_register , name='dept_register'),
    path('dept_login/', views.dept_login,name='dept_login'),
    # path('dept/dept_login/dispstu1/',views.dispstu1,name='dispstu1'),
    # path('dept/dept_login/usd1/',views.usd1,name='usd1'),
    path('student_login/usd/',views.usd,name='usd'),
    path('logout/', views.pagelogout, name='logout'),
    path('student_login/dispstu/',views.dispstu,name='dispstu'),
    
    path('', views.home, name='home'),
   
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path("password_reset/", views.password_reset_request, name="password_reset"),

    path('student_login/myresume',views.myresume,name='myresume'),
    path('student_login/displayResume',views.displayResume,name='displayresume'),
    # path('student_login/resume/',views.resume,name="resume"),
    path('student_login/apply',views.student_companyApplied,name='apply'),
    path('student_login/placementPrep/',views.placementPrep,name='PP'),
    path('quizindex/',views.quizindex,name='quizindex'),
    path("<int:myid>/", views.quiz, name="quiz"), 
    path('<int:myid>/data/', views.quiz_data_view, name='quiz-data'),
    path('<int:myid>/save/', views.save_quiz_view, name='quiz-save'),
    path('add_quiz/', views.add_quiz, name='add_quiz'),    
    path('add_question/', views.add_question, name='add_question'),  
    path('add_options/<int:myid>/', views.add_options, name='add_options'), 
    path('results/', views.results, name='results'),    
    path('delete_question/<int:myid>/', views.delete_question, name='delete_question'),  
    path('delete_result/<int:myid>/', views.delete_result, name='delete_result'),    
    path('student/student_login/offerletter',views.offerletter,name='Upload'),
    path('view',views.show_file,name='view'),
    path('student_login/placementPrep/java',views.java,name='java'),
    path('student_login/placementPrep/c',views.c,name='c'),
    path('student_login/placementPrep/dbms',views.Dbms,name='dbms'),
    path('student_login/placementPrep/cn',views.Cn,name='cn'),
    path('student_login/placementPrep/algo',views.Algo,name='algo'),
    path('student_login/placementPrep/os',views.Os,name='os'),
    path('student_login/placementPrep/ds',views.Ds,name='ds'),
    path('student_login/placementPrep/others',views.Other,name='others'),
    path('dept_register/' , views.dept_register , name='dept_register'),
    path('dept_login/', views.dept_login,name='dept_login'),
    path('dept_login/index/',views.index, name='index'),
    path('dept_login/index1/',views.index1, name='index1'),
    path('dept_login/index2/',views.index2, name='index2'),
    path('dept_login/index3/',views.index3, name='index3'),
    path('dept_login/index4/',views.index4, name='index4'),
    path('dept_login/index5/',views.index5, name='index5'),
    path('dept_login/index6/',views.index6, name='index6'),
    path('dept_login/index7/',views.index7, name='index7'),
    path('dept_login/index1/upload1/',views.upload1,name='upload1'),
    path('dept_login/index2/upload2/',views.upload2,name='upload2'),
    path('dept_login/index3/upload3/',views.upload3,name='upload3'),
    path('dept_login/index4/upload4/',views.upload4,name='upload4'),
    path('dept_login/index5/upload5/',views.upload5,name='upload5'),
    path('dept_login/index6/upload6/',views.upload6,name='upload6'),
    path('dept_login/index7/upload7/',views.upload1,name='upload1'),
    path('dept_login/index/upload/',views.upload,name='upload'),
    path('student_login/display/',views.display,name='display'),
]

crs/urls.py
from django.contrib import admin
from django.urls import path ,include
#from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('campus.urls')),
    # path('student/student_register/', include('campus.urls')),
    # path('student/student_login/',include('campus.urls')),
    # path('dept/dept_register/', include('campus.urls')),
    # path('dept/dept_login/',include('campus.urls')),
    # path('student/student_login/usd/',include('campus.urls')),
    # path('logout/',include('campus.urls')),
    # path('student/student_login/dispstu/', include('campus.urls')),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='campus/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="campus/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='campus/password/password_reset_complete.html'), name='password_reset_complete'),      
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus/models.py
from django.core.validators import MaxValueValidator,MinValueValidator,MaxLengthValidator,MinLengthValidator
from django.db import models
from django.contrib.auth.models import  AbstractUser
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from django import forms
import random
done = (
    ('yes', 'yes'),
    ('no', 'no'),
)

# class Student_Details(models.Model):
#     branch_choices = (
#         ('it', 'information_technology'),
#         ('me', 'mech'),
#         ('ce', 'civil'),
#         ('eee', 'eee'),
#         ('ece', 'ece'),
#         ('ch', 'chemical'),
#         ('cse', 'cse'),
#     )
#     gender = (
#         ('male', 'male'),
#         ('female', 'female'),
#         ('others','others'))

#     username=models.CharField(max_length=9,blank=False,help_text="enter username ex:y16it***",default="y1")
#     name = models.CharField(max_length=30, blank=False, help_text='*required',default="full name")
#     image = models.ImageField(default='default.jpg', upload_to='profile_picsnew')
#     phone_number = models.CharField(max_length=10,help_text='*required')
#     fathers_name = models.CharField(max_length=30, blank=False, help_text='*required')
#     mothers_name = models.CharField(max_length=30, blank=False, help_text='*required')
#     gender=models.CharField(blank=False, choices=gender,max_length=10)
#     place = models.CharField(max_length=30, blank=False)
#     branch = models.CharField(blank=False, choices=branch_choices, max_length=10)
#     cgpa_Btech = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
#     class_10_cgpa = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
#     class_12_percentage = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(100)],blank=False,help_text='*required')
#     certifications_count = models.IntegerField(blank=False)
#     internship = models.CharField(blank=False, choices=done,max_length=10)
#     languages = models.CharField(max_length=100, blank=False, help_text='*required')
#     sop = models.CharField(max_length=500, default="statement of purpose", help_text='*required')
#     dob = models.DateField(blank=True, help_text='*format is YYYY-MM-DD', )
#     email = models.EmailField(max_length=254, blank=False, help_text='Required. Inform a valid email address.',default="anudeep.insvirat@gmail.com")
#     skills=models.CharField(max_length=100, blank=False,default="java")
#     hobbies=models.CharField(max_length=100, blank=False,default="dance")
#     about=models.TextField(default="about ur self")
    
#     def __str__(self):
#        return self.username

class stu_details(models.Model):
    branch_choices = (
        ('it', 'information_technology'),
        ('me', 'mech'),
        ('ce', 'civil'),
        ('eee', 'eee'),
        ('ece', 'ece'),
        ('ch', 'chemical'),
        ('cse', 'cse'),
    )
    gender = (
        ('male', 'male'),
        ('female', 'female'),
        ('others','others'))

    username=models.CharField(max_length=10,blank=False, help_text="enter username ex:y16it***",default="y1")
    name = models.CharField(max_length=30, blank=False, help_text='*required',default="full name")
    # image = models.ImageField(default='default.jpg', upload_to='profile_picsnew')
    phone_number = models.CharField(max_length=10, help_text='*required')
    fathers_name = models.CharField(max_length=30, blank=False, help_text='*required')
    mothers_name = models.CharField(max_length=30, blank=False, help_text='*required')
    gender=models.CharField(blank=False, choices=gender,max_length=10)
    place = models.CharField(max_length=30, blank=False)
    branch = models.CharField(blank=False, choices=branch_choices, max_length=10)
    cgpa_Btech = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
    class_10_cgpa = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
    class_12_percentage = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(100)],blank=False,help_text='*required')
    certifications_count = models.IntegerField(blank=False)
    internship = models.CharField(blank=False, choices=done,max_length=10)
    languages = models.CharField(max_length=100, blank=False, help_text='*required')
    sop = models.CharField(max_length=500, default="statement of purpose", help_text='*required')
    dob = models.DateField(blank=False, help_text='*format is YYYY-MM-DD',)
    email = models.EmailField(max_length=254, blank=False, help_text='Required. Inform a valid email address.',default="anudeep.insvirat@gmail.com")
    skills=models.CharField(max_length=100, blank=False,default="java")
    hobbies=models.CharField(max_length=100, blank=False,default="dance")
    about=models.TextField(default="about ur self")
    
    def __str__(self):
       return self.username

class dept_details(models.Model):
   
    username=models.CharField(max_length=9,blank=False,help_text="enter username ex:y16it***",default="y1")
    name = models.CharField(max_length=30, blank=False, help_text='*required',default="full name")
    dob = models.DateField(blank=False, help_text='*format is YYYY-MM-DD', )
    email = models.EmailField(max_length=254, blank=False, help_text='Required. Inform a valid email address.',default="anudeep.insvirat@gmail.com")

    def __str__(self):
       return self.username



class comp_details(models.Model):
    username=models.CharField(max_length=30,blank=False , help_text='*required')
    company_name = models.CharField(max_length=30, blank=False, help_text='*required')
    est_year = models.CharField(max_length=4, blank=False, help_text="*required")
    hr_name = models.CharField(max_length=30, blank=False, help_text='*required')
    hr_phn = models.CharField(max_length=10,validators=[MinValueValidator(10),MaxValueValidator(10)], blank=False, help_text='*required')
    headquaters = models.CharField(max_length=30,blank=False, help_text='*required')
    about = models.CharField(max_length=1000, blank=False, help_text='*required')
    type = models.CharField(max_length=100, blank=False)
    email = models.EmailField(max_length=254,blank=False, help_text='Required. Inform a valid email address.')

    def __str__(self):
        return self.username

class job_pos(models.Model):
    job_id=models.CharField(max_length=30, blank=False, help_text='*required',unique=True)
    username = models.CharField(max_length=30, blank=False, help_text='*required')
    company_name = models.CharField(max_length=30, blank=False, help_text='*required')
    designation = models.CharField(max_length=30, blank=False, help_text='*required')
    salary=models.IntegerField( blank=False, help_text='*required')
    bond_years=models.IntegerField( blank=False, help_text='*required')
    information_technology= models.CharField(blank=False, choices=done, max_length=10)
    mech= models.CharField(blank=False, choices=done, max_length=10)
    civil= models.CharField(blank=False, choices=done, max_length=10)
    eee = models.CharField(blank=False, choices=done, max_length=10)
    ece= models.CharField(blank=False, choices=done, max_length=10)
    chemical= models.CharField(blank=False, choices=done, max_length=10)
    cse= models.CharField(blank=False, choices=done, max_length=10)

    def __str__(self):
        return self.job_id


class applied_jobs(models.Model):
    company_id = models.CharField(max_length=30, blank=False, help_text='*required' ,default="company id")
    job_id = models.CharField(max_length=30, blank=False, help_text='*required',default="job id")
    student_id= models.CharField(max_length=9, blank=False, help_text="enter username ex:y16it***", default="y1")

    def __str__(self):
        return self.job_id


# User.student = property(lambda p: stu_details.objects.get_or_create(user=p)[0])


#Quiz
class Quiz(models.Model):
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=500)    
    number_of_questions = models.IntegerField(default=1)
    time = models.IntegerField(help_text="Duration of the quiz in seconds", default="1")
    
    def __str__(self):
        return self.name

    def get_questions(self):
        return self.question_set.all()
    
class Question(models.Model):
    content = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content
    
    def get_answers(self):
        return self.answer_set.all()
    
    
class Answer(models.Model):
    content = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"question: {self.question.content}, answer: {self.content}, correct: {self.correct}"
    
class Marks_Of_User(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    
    def __str__(self):
        return str(self.quiz)

class Offer_letter(models.Model):
    ids = models.AutoField(primary_key=True)
    # usn = models.ForeignKey(stu_details, on_delete = models.CASCADE)
    usn = models.CharField(max_length=255)
    # company_selected = models.CharField(max_length=255)
    my_file = models.FileField(upload_to='')
    
    def __str__(self):
        return self.usn
    
class Java(models.Model):
    f_name=models.CharField(max_length=255)
    myfiles=models.FileField(upload_to="")
    

    def __str__(self):
        return self.f_name

class C(models.Model):
    f_name=models.CharField(max_length=255)
    myfiles=models.FileField(upload_to="")

    def __str__(self):
        return self.f_name

        

campus/templates/campus/OfferLetterUpload.html
{%extends 'campus/base.html'%}
{%block head%}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{%endblock%}
       {%block body_block%}
       <div class="container mt-5">
           <form  action="{% url 'Upload' %}" method="POST" enctype="multipart/form-data">
            {% comment %} style="text-align:center;" {% endcomment %}
              <h3 style="text-align:center; font-family:Georgia, 'Times New Roman', Times, serif;" >Upload Your Offer Letter!</h3>
               <div class="form-group" style="font-family:Georgia, 'Times New Roman', Times, serif;">
                 <label for="{{form.file_name.id_for_label}}">Your USN</label>
                 {{form.file_name}}         
               </div>

               {% comment %} <div class="form-group">
                <label for="{{form.company_selected.id_for_label}}">Company you got selected</label>
                {{form.company_selected}}         
              </div> {% endcomment %}
                
               <div class="form-group">
                   <label for="{{form.files_data.id_for_label}}">File</label>
                   {{form.files_data}}         
                 </div>
                 {% csrf_token %}
               
               
               <button type="submit" class="btn btn-primary">Submit</button>
             </form>
             
       
       </div>
       <br>
       <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
       

       {%endblock%}

campus/templates/campus/applyjob.html
{% extends "campus/base.html" %}

{% block body_block %}

      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
          
            <br>
            <h2> APPLY FOR JOB!</h2>
          </div>
        </div>
      </div>
</div>
<div class="container">

  <div class="jumbotron">
      <h1>{{ s }}</h1>
      <form method="post">
           {% csrf_token %}
       
            MINIMUM SALARY:<input type="number" size="10" name="salary"  style="font-size: 1rem;font-family: Comic Sans MS, cursive, sans-serif">
            MAXIMUM BOND YEARS:<input type="number" size="10" name="years"  style="font-size: 1rem;font-family: Comic Sans MS, cursive, sans-serif">
            <input type="submit" class="btn btn-primary" value="SEARCH">
        </form>
        <br>
      <table border="1px" style="text-align: center;border-collapse: collapse;background-color:rgb(96, 224, 214);"width=100%">
          <tr >
              <th style="font-size:1.5rem;color: #123027cc">Company </th>
              <th style="font-size:1.5rem;color: #123027cc">Designation</th>
                   <th style="font-size:1.5rem;color: #123027cc">Salary</th>
              <th style="font-size:1.5rem;color: #123027cc">Bond years</th>
              <th style="font-size:1.5rem;color:rgb(44, 143, 5)">Apply</th>
    
          </tr>
          {%  for i in y %}
          <tr>
              <td>{{ i.company_name }}</td>
          <td>{{ i.designation }}</td>
          <td>{{ i.salary }}</td>
          <td>{{ i.bond_years }}</td>
              <td><a href="http://127.0.0.1:8000/student/student_login/applyjob/{{ i.job_id }}/" target="popup" onclick="window.open('http://127.0.0.1:8000/student/student_login/applyjob/{{ i.job_id }}/','popup','width=600,height=600');" return false; >APPLY</a></td>
          </tr>
          {% endfor %}
      </table> 


  </div>
  
</div>

{% endblock %}

campus/templates/campus/deptMain.html
<!Doctype html>
{% extends "campus/base.html" %}

{%block body_block%}

      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
          
            <br><br>
            <h2> Hello {{ user.username|title }}!</h2>
          </div>
        </div>
      </div>
</div>
<div class="container">

  <div class="jumbotron">
      <table class="pos2">
          <tr>
              <td  ><a href="index/" class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">JAVA</b></a></td>
              <td><a href="/quizindex/" class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">QUIZ</b></a></td>
            </tr><tr>
          <td ><a href="index1/ " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">C PROGRAMMING</b></a></td></tr><tr>
            <td  ><a href="index2/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">DBMS</b></a></td></tr><tr> 
        <td  ><a href="index3/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">COMPUTER NETWORKS</b></a></td></tr><tr>
            <td  ><a href="index4/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">OPERATING SYSTEM</b></a></td></tr><tr>
                <td  ><a href="index5/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">ALGORITHMS</b></a></td></tr><tr>
                    <td  ><a href="index6/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">OTHER</b></a></td></tr><tr>
                    </tr>
                    <td  ><a href="index7/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">DS</b></a></td></tr><tr>
                    </tr>
                </tr>
            </tr>
          </tr>
      </table>
  
  </div>
  
</div>

{% endblock %}

campus/templates/campus/dept_login.html
<!DOCTYPE html>
{% extends "campus/base.html" %}

{%block body_block%}

      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
          
            <br><br>
            <h2>DEPARTMENT LOGIN HERE!</h2>
          </div>
        </div>
      </div>

<div class="container">

  <div class="jumbotron">
      <table class="hi">
          <tr>
      
           <form method="post">
      {% csrf_token %}
      {{form.as_table}}
      {% csrf_token %}
      
          <tr>  <td><p><button type="submit"  class="btn btn-lg btn-primary  d-inline-flex "">Login</button></p></td></tr>
      </form>
              </tr>
              <tr>
              <td><center>
      <a href="http://127.0.0.1:8000/dept/dept_register " class=" d-inline-flex "  style="color:green"><b>New user? Register here</b></a>
              </center></td>
      </tr>
      </table>
  </div>
  
</div>

{% endblock %}

campus/templates/campus/deptlog.html
<!Doctype html>
{% extends "campus/base.html" %}

{%block body_block%}

      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
          
            <br><br>
            <h2> Hello {{ user.username|title }}!</h2>
          </div>
        </div>
      </div>
</div>
<div class="container">

  <div class="jumbotron">
      <table class="pos2">
          <tr>
              <td  ><a href="http://127.0.0.1:8000/dept/dept_login/dispstu1/ " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">View profile</b></a></td></tr><tr>
          <td ><a href="http://127.0.0.1:8000/dept/dept_login/usd1/ " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">Update Profile</b></a></td></tr><tr>
     
          </tr>
      </table>
  
  </div>
  
</div>

{% endblock %}

campus/templates/campus/placementPrep.html
{% extends 'campus/base.html' %}

{% block head%}
    <title>Placement Preparation</title>

    <style>
        
        h1 {
            text-align: center;
            font-size: 40px;
          }          
        body{
            background-color: rgb(209, 222, 226);
            text-align: center;
        }
    </style>
    {% endblock head %}

{% block body_block %}
    <div class="card-body bg-light">
        <h1 class=ex1><center>Welcome to placement Preparation!</center></h1>
            <h3>
                
                    <div class="card-body bg-dark"><center>
                        {% comment %} <br><a href="quiz/">Aptitude Quiz</a><br> {% endcomment %}
                        <br><a href="c">C</a><br>
                        {% comment %} <br><a href="datastructures/">Data structures</a><br> {% endcomment %}
                        <br><a href="os">Operating Systems</a><br>
                        <br><a href="java">Java</a><br>
                        <br><a href="cn">Computer Networks</a><br>
                        <br><a href="dbms">Database Management System</a><br>
                        <br><a href="algo">Algorithms</a><br>
                        <br><a href="others">Other</a><br>
                    </center>
                    </div>
                
            </h3>
    </div>
{% endblock body_block %}

campus/templates/campus/usd.html
         <!DOCTYPE html>
         {%extends "campus/base.html"%}
         
         {%block body_block%}
             <div class="container-fluid">
               
                   <div class="row">
                       <div class="col-md-6 mx-auto text-center mb-5 section-heading">
                        
                         <br><br>
                         <h2>Modify Details</h2>
                       </div>
                     </div>
                   </div>
                   <div class="container">
                   <div class="jumbotron">
                      

                      {% if form.errors %}
                      {% for field in form %}
                          {% for error in field.errors %}
                              <div class="alert alert-danger">
                                  <strong>{{ error|escape }}</strong>
                              </div>
                          {% endfor %}
                      {% endfor %}
                      {% for error in form.non_field_errors %}
                          <div class="alert alert-danger">
                              <strong>{{ error|escape }}</strong>
                          </div>
                      {% endfor %}
                  {% endif %}
                  
                  
                           <form method="post" >
                              {% csrf_token %}
                               <table>
                                    <tr><th><label for="id_phone_number">Phone number:</label></th><td><input type="text" name="phone_number" maxlength="10" minlength="10" required id="id_phone_number"  value="{{ x }}"></td></tr>
                                    <tr><th><label>name</label></th><td><input type="text" name="name" value="{{ name }}"></td></tr>
                                    
                                    <tr><th><label>DOB</label></th><td><input type="date" name="dob" maxlength="10" minlength="10" value="{{ db }}"></td></tr>
                                    <tr><th><label>Father's name</label></th><td><input type="text" name="fathers_name" maxlength="10" minlength="10" value="{{ fn }}"></td></tr>
                                    <tr><th><label>Mother's Name</label></th><td><input type="text" name="mothers_name" maxlength="10" minlength="10" value="{{ mn }}"></td></tr>
                                    <tr><th><label>Gender</label></th>
                                        <td>
                                        <input type="radio" name="gender" value="female" >female
                                        <input type="radio" name="gender" value="male" >male
                                        <input type="radio" name="gender" value="others" >others
                                        </td>
                                    </tr> 
                                    <tr><th><label>Branch</label></th><td><input type="text" name="branch" maxlength="10" minlength="10" value="{{ b }}"></td></tr>
                                    <tr><th><label>BGPA Btech</label></th><td><input type="text" name="cgpa_Btech" maxlength="10" minlength="10" value="{{ cb }}"></td></tr>

                                    <tr><th><label>Place</label></th><td><input type="text" name="place" maxlength="10" minlength="10" value="{{ p }}"></td></tr>
                                    <tr><th><label>Class 10 CGPA</label></th><td><input type="number" name="class_10_cgpa" value="{{ c10 }}"></td></tr>
                                    <tr><th><label>Class 12 Percentage</label></th><td><input type="number" name="class_12_percentage" value="{{ c12 }}" ></td></tr>
                                    <tr><th><label>Internship</label></th><td><input type="text" name="internship" value="yes/no" value="{{ i }}"></td></tr>
                                    <tr><th><label>Certification count</label></th><td><input type="number" name="certifications_count" maxlength="10" minlength="10" value="{{ cc }}"></td></tr>
                                    <tr><th><label>languages</label></th><td><input type="text" name="languages" maxlength="10" minlength="10" value="{{ l }}"></td></tr>
                                    <tr><th><label>Email</label></th><td><input type="email" name="email" value="{{ e }}"></td></tr>
                                    <tr><th><label for="id_sop" value="{{ y }}">Sop:</label></th><td><textarea rows="10" cols="50" name="sop"  maxlength="500" required id="id_sop" value="{{ x }}"></textarea></td></tr>
                                    
                                   <tr>
                                      <td></td>
                                       <td><br><button type="submit" name="submit" value="Register" style="font-size: 1.5rem;font-family: Comic Sans MS, cursive, sans-serif"  class="btn btn-danger">MODIFY</button></td>
                                  </tr>

                               </table>
                           </form>
                       </div>
                   </div>
                   
         
         
               </div>
               
         
         
         {%endblock%}
          